package main

import "fmt"

/*
 You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
Seen this question in a real interview before?
1/5*/

func findTheDifference(s string, t string) byte {
	ascii := [128]int{}
	for i := 0; i < len(s); i++ {
		ascii[s[i]]++
	}
	for i := 0; i < len(t); i++ {
		if ascii[t[i]] == 0 {
			return t[i]
		}
		ascii[t[i]]--
	}
	return t[len(s)]
}

func main() {
	s := "abcd"
	t := "abcde"
	fmt.Println(string(findTheDifference(s, t)))
	s = ""
	t = "y"
	fmt.Println(string(findTheDifference(s, t)))

}
